//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplication1 {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("WebApplication1.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///	&quot;ProjectId&quot;: &quot;bwrx-dev&quot;,
        ///	&quot;IpAddressHeaderName&quot;: &quot;ipaddress&quot;,
        ///	&quot;CloudFunctionHttpBaseAddress&quot;: &quot; https://europe-west2-bwrx-dev.cloudfunctions.net/input-sit-0&quot;,
        ///	&quot;BlacklistUri&quot;: &quot;https://europe-west2-bwrx-dev.cloudfunctions.net/blacklist-sit-0&quot;,
        ///	&quot;BlacklistCountUri&quot;: &quot;https://europe-west2-bwrx-dev.cloudfunctions.net/recordcount-sit-0&quot;,
        ///	&quot;BlacklistRangesUri&quot;: &quot;https://europe-west2-bwrx-dev.cloudfunctions.net/blacklistranges-sit-0&quot;,
        ///	&quot;GetBlacklistTimeInterval&quot;: 5,
        ///	&quot;WhitelistUri&quot;: &quot;https://europe-we [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string ClientConfigSettings {
            get {
                return ResourceManager.GetString("ClientConfigSettings", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to {
        ///  &quot;type&quot;: &quot;service_account&quot;,
        ///  &quot;project_id&quot;: &quot;bwrx-dev&quot;,
        ///  &quot;private_key_id&quot;: &quot;d5102f250f1d02e94271df6383f52bcea3158dab&quot;,
        ///  &quot;private_key&quot;: &quot;-----BEGIN PRIVATE KEY-----\nMIIEvgIBADANBgkqhkiG9w0BAQEFAASCBKgwggSkAgEAAoIBAQCdqvWuHN+DIt+W\nU8me40jiagtDd19UujOo/al4W62pZscnqplbnfqIHCRMPck2ICOLljaO8wnntTDA\nwh6lGGkfPPQpk3IL24ijJpv2Q1L7KUI7IAC973PJilT+e0o1WZ/bvOogEiNidFZO\nAdzUenoQEI/CA/JIUY40s/9GEIQoR0v+uon47VQEkaG8G0DOyoGHhG1G9bGzdK24\nCxI9A4lISg12ymQQGL+w/N4h9GjjIOPivVi1qV9AAGYx/IzWmNxY69GvDY0K27lo\ngSYHFgGU [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string Credentials {
            get {
                return ResourceManager.GetString("Credentials", resourceCulture);
            }
        }
    }
}
